pipeline {
    agent { label "${node}" }

    parameters {
        string(name: 'VERSION', defaultValue: '', description: 'Version number for the docker image')
    }

    stages {
        stage('dockerhub pull') {
            steps {
                sh "sudo docker pull sivanmarom/test:flask_image-\${params.VERSION}"
                sh "sudo docker run -it --name flaskApp -p 5000:5000 -d sivanmarom/test:flask_image-\${params.VERSION}"
            }
        }
    }
}