pipeline {
    agent { label "${params.node}" }

    stages {
        stage('dockerhub pull') {
            steps {
                sh 'sudo docker pull sivanmarom/test:flask_image-4.0'
                sh 'sudo docker run -it --name flaskApp -p 5000:5000 -d sivanmarom/test:flask_image-3.0'

            }
        }
    }
}
